# Generated by Django 5.0 on 2023-12-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geoWorld", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
